### PR TITLE
Swap symbols for PS5 Create and Options buttons

### PR DESCRIPTION
**Pull request by benwilson34**
Hi! Love these icons 👍 just wanted to make a small adjustment - the symbols on the PS5 Create and Options buttons seem to be swapped judging from the angle of the button outlines. The Create button is the left-leaning one and the Options button is the right-leaning one:

Here's the change:
image

I've only changed the source svg file for now, let me know if all looks good and I can prepare the individual svg and png files. Thanks! 😁

### CODE REVIEW

**Comment by lopopylopy** [comment]
I seem to have issues with PS5 prompts... #12 

This looks great, thank you for making a fix!

To merge though, I'll need updates to 
 - `previews/preview.svg` and `previews/ps5_preview.svg` (and then exports to png for both). This can be done by copy/pasting the new icons over the olds ones in the svg, and
 - the corresponding `/png` and `/svg` icons.

**Comment by benwilson34** [comment]
Ok, I've updated all but the preview pngs. I'm missing the Megusto font so the "B" in "Mr. Breakfast" isn't quite right:
ps5_preview-temp

If that's the only place the font is used, could you convert that "B" to a path instead of text (like with the "M") so that Megusto isn't a dependency? I found some sites offering a free download of the font but I don't necessarily trust them.

**Comment by lopopylopy** [comment]
Yes I can do that! `/meta/center_title` is a path version of the "Mr. Breakfast," but I'll go through this fork and make them paths

**Comment by lopopylopy** [comment]
And thank you for your README copy edits and editions 😁

**Comment by lopopylopy** [comment]
I mistakenly edited main and not this PR. Let me get that fixed. Sorry for the inconvenience

**Comment by lopopylopy** [comment]
> I mistakenly edited main and not this PR. Let me get that fixed. Sorry for the inconvenience

Done 👍

**Comment by benwilson34** [comment]
Awesome, thank you!

**Pull request merged**
